// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu'];
    LeftNavBar: typeof import('./src/components/LeftNavBar/LeftNavBar.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
